version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"